services:
  traefik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - globalgen_local_nw
    command:
      - --providers.docker
  
  api: &api
    build:
      context: .
      dockerfile: ./backend/docker/local/fastapi/Dockerfile
    volumes:
      - .:/src
      - ./backend/app/logs:/src/backend/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - globalgen_local_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - globalgen_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - globalgen_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - globalbank_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - globalgen_local_nw
  
  redis:
    image: docker.io/redis:7.0-alpine
    command: redis-server --appendonly yes
    networks:
      - globalgen_local_nw
  
  rabbitmq:
    image: docker.io/rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - globalbank_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - globalgen_local_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.routers.rabbitmq.service=rabbitmq-service"
      - "traefik.http.services.rabbitmq-service.loadbalancer.server.port=15672"

  celeryworker:
    <<: *api
    ports: []
    command: /start-celeryworker.sh

  flower:
    <<: *api
    ports:
      - "5555:5555"
    volumes:
      - globalbank_flower_data:/data
    command: /start-flower.sh
    depends_on:
      - redis
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
      - "traefik.http.routers.flower.service=flower-service"
      - "traefik.http.services.flower-service.loadbalancer.server.port=5555"
  
  celerybeat:
    <<: *api
    ports: []
    command: /start-celerybeat.sh

networks:
  globalgen_local_nw:
    external: true

volumes:
  globalbank_data:
  globalgen_mailpit_data:
  globalbank_rabbitmq_data:
  globalbank_flower_data: